setwd("C:/Users/Andrew/Desktop/Exploratory data analysis/Project 1")
a<-read.csv("household_power_consumption.txt", sep=';', na.strings='?')
a$Date<-as.Date(a$Date, format="%d/%m/%Y")
b<-subset(a, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
b$Date2<-as.POSIXct(paste(as.Date(b$Date), b$Time))
par(mfrow=c(1,1))
with(b, {plot(Sub_metering_1~Date2, type="l",xlab="",ylab="Energy sub metering") 
         lines(Sub_metering_2~Date2,col='Red')
         lines(Sub_metering_3~Date2,col='Blue')})
legend("topright", col=c("black", "red", "blue"),lty=1,lwd=2,cex=.75,legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file="plot3.png", height=480, width=480, res=65)
dev.off()
rm(a,b)