setwd("C:/Users/Andrew/Desktop/Exploratory data analysis/Project 1")
a<-read.csv("household_power_consumption.txt", sep=';', na.strings='?')
a$Date<-as.Date(a$Date, format="%d/%m/%Y")
b<-subset(a, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
b$Date2<-as.POSIXct(paste(as.Date(b$Date), b$Time))
par(mfrow=c(1,1))
plot(b$Global_active_power~b$Date2, type="l",xlab="", ylab="Global Active Power (kilowatts)")
dev.copy(png, file="plot2.png", height=480, width=480)
dev.off()
rm(a,b)