setwd("C:/Users/Andrew/Desktop/Exploratory data analysis/Project 1")
a<-read.csv("household_power_consumption.txt", sep=';', na.strings='?')
a$Date<-as.Date(a$Date, format="%d/%m/%Y")
b<-subset(a, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
b$Date2<-as.POSIXct(paste(as.Date(b$Date), b$Time))
par(mfrow=c(2,2), mar=c(4,4,2,1), oma=c(0,1,2,0))
with(b, {plot(Global_active_power~Date2, type="l",xlab="",ylab="Global Active Power")
        plot(Voltage~Date2, type="l",xlab="",ylab="Voltage")
        plot(Sub_metering_1~Date2, type="l",xlab="",ylab="Energy sub metering")
        lines(Sub_metering_2~Date2,col='Red')
        lines(Sub_metering_3~Date2,col='Blue')
        legend("topright", col=c("black", "red", "blue"),lty=1,lwd=2,cex=.5,bty="n",
               legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
        plot(Global_reactive_power~Date2, type="l",xlab="",ylab="Global_rective_power")})
dev.copy(png, file="plot4.png", height=480, width=480,res=70)
dev.off()
rm(a,b)