setwd("C:/Users/Andrew/Desktop/Exploratory data analysis/Project 1")
a<-read.csv("household_power_consumption.txt", sep=';', na.strings='?')
a$Date<-as.Date(a$Date, format="%d/%m/%Y")
b<-subset(a, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
par(mfrow=c(1,1))
hist(b$Global_active_power,col="Red",main="Global Active Power",xlab="Global Active Power (kilowatts)",ylab="Frequency")
dev.copy(png, file="plot1.png", height=480, width=480)
dev.off()
rm(a,b)